version: '3'
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=photobooth
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

  photoserver:
    depends_on:
      - mongodb
    image: photoserver
    labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.photoserver.rule=Host(`host.example.com`)"
      #- "traefik.http.routers.photoserver.entrypoints=https"
      #- "traefik.http.routers.photoserver.tls=true"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    volumes:
      - ./content:/usr/src/app/content

networks:
  default:
    name: traefik
    external: true
volumes:
  db:
